name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  ui-and-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.11.1'

      - name: Install Cypress dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress

      - name: Give Cypress execute permission
        working-directory: ./ui-tests
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

    
      - name: Install Newman
        run: npm install -g newman

      - name: Start local API server
        run: node ./server.js &

      - name: Wait for server to start
        run: sleep 5

      - name: Run Postman collection
        run: newman run ./api-tests/postman-collections.json

  k6-performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6
          k6 version

      - name: Run k6 performance test
        run: k6 run ./performance-tests/create_order_test.js